name: Build Kernel Courbet

on:
  workflow_dispatch:
    inputs:
      kernel_url:
        description: 'Kernel github url perf-kernel: https://github.com/pratikkabra143/kernel_xiaomi_courbet.git, courbet: https://github.com/pratikkabra143/kernel_xiaomi_sm7150.git, ksun: , sukisu: '
        required: true
        default: 'https://github.com/pratikkabra143/kernel_xiaomi_sm7150.git'
        type: string
      kernel_branch:
        description: "github branch like 'sixteen'"
        required: true
        default: 'sixteen'
        type: string
      kernel_type:
        description: 'Kernel Type'
        required: true
        default: 'courbet'
        type: string
        # options:
        # - 'ksun'
        # - 'sukisu'
        # - 'courbet'
        # - 'perfkernel'
      recurse_submodule:
        description: "some kernel source use submodule(true/false)"
        required: true
        default: false
        type: boolean
      is_release:
        description: "Kernel Release at github true or false"
        required: true
        default: false
        type: boolean
        
jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      KERNEL_NAME: "courbet"
      KERNEL_DIR: "courbet-kernel"
      ARCH: "arm64"
      SUBARCH: "arm64"
      KBUILD_BUILD_USER: "pratikkabra143"
      KBUILD_BUILD_HOST: "github"
      KERNEL_URL: ${{ github.event.inputs.kernel_url }}
      KERNEL_BRANCH: ${{ github.event.inputs.kernel_branch }}
      KERNEL_TYPE: ${{ github.event.inputs.kernel_type }}
      IS_RELEASE: ${{ github.event.inputs.is_release }}
      RECURSE_SUBMODULE: ${{ github.event.inputs.recurse_submodule }}
      KERNEL_VERSION: "4.14.356"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: update and download required packages
      run: sudo apt update && sudo apt install -y git bc bison flex libssl-dev make automake build-essential curl zip clang lld gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi libdebuginfod1 elfutils

    - name: clone kernel source
      run: |
        cd ${GITHUB_WORKSPACE}
        if [ "$RECURSE_SUBMODULE" = "true" ]; then
          git clone --recurse-submodules ${KERNEL_URL} -b ${KERNEL_BRANCH} ${KERNEL_DIR}
        else
          git clone ${KERNEL_URL} -b ${KERNEL_BRANCH} ${KERNEL_DIR}
        fi
    - name: build kernel from source
      run: |
        cd ${GITHUB_WORKSPACE}/${KERNEL_DIR}
        export ARCH=${ARCH}
        make O=out ${KERNEL_NAME}_defconfig
        make -j$(nproc --all) \
        O=out CC=clang \
        CROSS_COMPILE=aarch64-linux-gnu- \
        CROSS_COMPILE_ARM32=arm-linux-gnueabi- \
        CONFIG_NO_ERROR_ON_MISMATCH=y
        BUILD_TIME=$(date '+%Y%m%d-%H%M%S')
        echo "BUILD_TIME=$BUILD_TIME" >> $GITHUB_ENV
        
        KERNEL_VERSION=$(make kernelversion)
        echo "KERNEL_VERSION=$KERNEL_VERSION" >> $GITHUB_ENV
        mkdir ${GITHUB_WORKSPACE}/output
        cp out/arch/arm64/boot/Image.gz ${GITHUB_WORKSPACE}/output/
        cp out/arch/arm64/boot/dtb.img ${GITHUB_WORKSPACE}/output/
        cp out/arch/arm64/boot/dtbo.img ${GITHUB_WORKSPACE}/output/
        cd ${GITHUB_WORKSPACE}
    - name: create anykernel3 zip
      run: |
        git clone https://github.com/pratikkabra143/AnyKernel3.git -b ${KERNEL_TYPE,,}
        cp output/* AnyKernel3/
        cd AnyKernel3
        # Use updated KERNEL_TYPE for the zip file name
        zip -r9 ../${{ env.KERNEL_TYPE }}-${{ env.KERNEL_BRANCH }}-${KERNEL_VERSION}-${KERNEL_NAME}-${BUILD_TIME}.zip * -x .git README.md *placeholder
        cd ${GITHUB_WORKSPACE}
    - name: upload kernel output
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.KERNEL_TYPE }}-${{ env.KERNEL_VERSION }}-${{ env.KERNEL_BRANCH }}-${{ env.KERNEL_NAME }}
        path: ${{ env.KERNEL_TYPE }}*.zip

    - name: Create release
      if: ${{ env.IS_RELEASE == 'true' }}
      uses: softprops/action-gh-release@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag_name: v${{ env.KERNEL_VERSION }}
        name: "Kernel Version ${{ env.KERNEL_VERSION }}"
        body: '${{ env.KERNEL_VERSION }}-${{ env.KERNEL_TYPE }}-${{ env.KERNEL_BRANCH }} for ${{ env.KERNEL_NAME }}'
        draft: false
        prerelease: false
        generate_release_notes: false
        files: ${{ env.KERNEL_TYPE }}*.zip
